version: '3'
services:
  reprocessbi:
    build: 
      context: https://github.com/VictorAlmeidaFonseca/reprocess-bi.git#main
      args:
        VTEX_TOKEN: UWDHKAFMALYNKRKIKHDNCOUACVKMWYJFCDNFFZSUFFLFYEVNRGVKHELFBCFPPSQBCTLHDFCLOJHXDPCXZXVPCYYYRIDCUCENOJCFTOJMDKWYWOCMAHPSXAZDUMPVBAQL
        VTEX_KEY: vtexappkey-samsungbrshop-IZZZJF 
        VTEX_ACCOUNTNAME: samsungbrshop 
    container_name: reprocessbi
    restart: always
    depends_on: 
     - elasticsearchlogs
    ports:
      - '3001:3001'
    environment:
      ELASTIC_HOST: 'http://elasticsearch01'
      ELASTC_PORT: 9200
      NODEPORT: 3001
      MONGO_URI : mongodb://samsung:P6WZOTteVKsyEpKH@samsung-shard-00-00-e8xxv.mongodb.net:27017,samsung-shard-00-01-e8xxv.mongodb.net:27017,samsung-shard-00-02-e8xxv.mongodb.net:27017/BI?ssl=true&replicaSet=Samsung-shard-0&readPreference=primary&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1&3t.uriVersion=3&3t.connection.name=Samsung-shard-0&3t.databases=BI,admin&3t.alwaysShowAuthDB=true&3t.alwaysShowDBFromUserRole=true&3t.sslTlsVersion=TLS
      MONGO_DB : BI
      MONGO_COLLECTION: expenses
      START_DATE: '01/01/2021'
      END_DATE: '02/02/2021'      
    networks:
      - log-elastic
      
  elasticsearchlogs:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.9.2'
    container_name: elasticsearchlogs
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      discovery.type: single-node
    networks:
      - log-elastic
      
  kibanalogs:
    image: 'docker.elastic.co/kibana/kibana:7.9.2'
    container_name: kibanalogs
    depends_on: 
     - elasticsearchlogs
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch01:9200'
      ELASTICSEARCH_HOSTS: 'http://elasticsearch01:9200'
    networks:
      - log-elastic
networks:
  log-elastic:
    driver: bridge